group_name: experiments
patch:
  x: 50
  y: 50
  z: 10

network:
  ngf: 26
  n_layers_D: 4
  ndf: 64

optimization:
  min_pixel: 0.2
  batch_size: 64
  learning_rate: 0.0001
  constant_for_a: 0.43714
  learning_rate_D_constant: 0.13189
  beta1: 0.5
  mixed_precision: True
  num_workers: 4
  lr_restart_epochs: 8
  lr_restart_mult: 2
  lr_min_G: 0.000002
  lr_min_D: 0.000001
  use_wasserstein: False
  use_lsgan: True
  use_hinge: False
  use_relativistic: False
  disc_update_freq: 3

training:
  visualize_features: False
  vis_freq: 10
  vis_max_channels: 16
  save_latest_freq: 200
  print_freq: 1
  patches_per_image: 64
  save_epoch_freq: 1
  niter: 50
  niter_decay: 50
  accumulation_steps: 1
  run_validation_interval: 5

losses:
  lambda_mmd: 0
  lambda_identity: 2.0
  lambda_cycle_a: 3.46434
  lambda_cycle_b: 1.99262
  lambda_ganloss_a: 3.52646
  lambda_ganloss_b: 3.57084
  lambda_domain_adaptation: 2.23
  lambda_vgg: 0
  lambda_feature_matching: 6.48035


  lambda_da_histogram: 1.91624
  lambda_da_contrast: 2.03817
  lambda_da_structure: 0.71725
  lambda_da_gradient: 0.12601
  lambda_da_ncc: 0.4271
  lambda_da_texture: 0.95491
  use_lambda_scheduler: False


  identity_phase_out_start: 0.2
  identity_phase_out_end: 0.6
  gan_phase_in_start: 0.03
  gan_phase_in_end: 0.3
  domain_adaptation_phase_in_start: 0.1
  domain_adaptation_phase_in_end: 0.5
  domain_adaptation_scale_max: 2
  cycle_adjust_start: 0.3
  cycle_adjust_end: 0.7
  cycle_scale_min: 0.8


  cycle_loss_type_1: l1
  cycle_loss_type_2: l2
  identity_loss_type_1: l2
  identity_loss_type_2: perceptual

model:
  use_stn: False
  use_residual: True
  use_full_attention: False